### PR TITLE
project pages

### PR DESCRIPTION
**Pull request by EngineerRunner**
pretty basic project pages with a turbowarp embed. i'll add the title and comments and stuff like that soon.

### CODE REVIEW

**Comment by redstone-scratch** [comment]
nice, thanks

**Comment by EngineerRunner** [comment]
now it doesn't need scratchDB, although there is still a toggle for it if you're running on something like replit which is blocked from scratch's api.

**Comment by redstone-scratch** [comment]
Nice, will review new changes

**Comment by redstone-scratch** [comment]
We're getting close to getting it merged, so it will be quicker when it's ready to merge

**Comment by EngineerRunner** [comment]
i still need to add a lot more. currently working on comments

**Comment by redstone-scratch** [comment]
Maybe you could add a feature using JS where you could quickly comment using Ctrl-Enter, just a thought

**Comment by EngineerRunner** [comment]
i think it's best to just release it without comments for now and build off of it. i'll just resolve the conflicts and push it now. (i'll add profile pictures when there's a user page to link to)

**Comment by EngineerRunner** [comment]
this is ready for merging, but somebody else should also test it first just in case.
just set it up like normal, and the project pages are at 127.0.0.1:3000/projects/[id]

**Comment by ajskateboarder** [comment]
This works as normal, LGTM

**Comment by redstone-scratch** [comment]
I'm going to focus on getting the `subforum-rework` branch merged ASAP then I'll focus on PRs and issues\

Please don't merge until I'm done (won't be long)

**Comment by EngineerRunner** [comment]
conflicts resolved, ima test then merge it

**Comment by EngineerRunner** [comment]
we're finally out of merge conflict hell

**Pull request merged**
