### PR TITLE
add project studio stuff on home page

### PR DESCRIPTION
**Pull request by ajskateboarder**
image

🚀 🚀 🚀 🚀

This might cause a merge conflict with EngineerRunner's fork

### CODE REVIEW

**Comment by ajskateboarder** [comment]
Oh and I had an absolutely miserable time editing the same CSS across multiple files
Hopefully a base CSS file comes around :)

**Comment by Darth-Ness** [comment]
In #16 I asked if that would be wanted. If so, I can start on a PR.

**Comment by redstone-scratch** [comment]
> Oh and I had an absolutely miserable time editing the same CSS across multiple files Hopefully a base CSS file comes around :)

Okay I won't delete the `master-styles` file, I'm going to reopen #16 lol

**Comment by redstone-scratch** [comment]
I'm going to focus on getting the `subforum-rework` branch merged ASAP then I'll focus on PRs and issues

Will open once I get back to it

**Comment by EngineerRunner** [comment]
ima merge the project page PR and see if I can resolve any conflicts with this

**Comment by redstone-scratch** [comment]
> There were some conflicts on my fork after redstone merged subform-rework, and it should be fixed now

Oof sorry

> Oh and I forgot to mention that I made some changes to the gruvbox CSS for consistency, like making the logo in the navbar the same color as the glow whenever you hover over it

Nice

**Pull request merged**
