### PR TITLE
Fix theming issues

### LINKED ISSUE #16: Problems With Theme Making
There is a master styles file, but it's empty. If you want I can make a PR that puts the theme stuff in the theme files.
And basic stuff in the master file. That way it's easier to develop new CSS features.

### PR DESCRIPTION
**Pull request by Darth-Ness**
This PR fixes #16

### CODE REVIEW

**Comment by Darth-Ness** [comment]
All right, this is ready for review. Let me know if one of the theme aren't rendering correctly.

**Comment by EngineerRunner** [comment]
aight i'll test it now

**Comment by EngineerRunner** [comment]
each theme is supposed to have a different font, but they are all just showing up as a default one.
[here's ](https://assets.scratch.mit.edu/get_image/.%2E/cc0db0a44fb7b9acb2b13a1c1380b5ba.png) [some ](https://assets.scratch.mit.edu/get_image/.%2E/ec77004c5780983ef301f1e87709fe74.png) [images](https://assets.scratch.mit.edu/get_image/.%2E/4b0fc887067a9eb5c714dc736e2d7a01.png)

**Comment by Darth-Ness** [comment]
Why Google Fonts?

**Comment by redstone-scratch** [comment]
> Why Google Fonts?

It's easy to use and they have a lot of fonts, plus it ensures compatibility across devices.

**Comment by redstone-scratch** [comment]
You can delete the Mynerve font, it's never used lmao

**Comment by redstone-scratch** [comment]
Btw I'd like the Hackerman theme to somehow stay as it was, I designed it on purpose that way, and also the Newspaper theme had some minor differences (5px border-radius instead of 10px and stuff like that)

**Review by ajskateboarder — APPROVED** [review]
I think this is ready to merge

**Pull request merged**
